# This file is autogenerated, any hand modifications will be lost!

# Makefile Paths Definitions
CWD := E:\open_source\NammaAUTOSAR
ROOT_PATH := E:\open_source\NammaAUTOSAR
MCU_STARTUP_PATH := E:\open_source\NammaAUTOSAR/submodules/MCAL/Mcu\src\bsp/startup/rp2040
MCU_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Mcu
ECUM_PATH := E:\open_source\NammaAUTOSAR/submodules\SL\EcuM
PORT_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Port
DIO_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Dio
SPI_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Spi
LIN_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Lin
ETH_PATH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Eth
ETHIF_PATH := E:\open_source\NammaAUTOSAR/submodules\ECU-AL\EthIf
TCPIP_PATH := E:\open_source\NammaAUTOSAR/submodules\SL\TcpIp
OS_PATH := E:\open_source\NammaAUTOSAR/submodules\SL\Os
OS_BUILDER_PATH := E:\open_source\NammaAUTOSAR\tools\os_builder


# Link Archive File Path Definitions
LIBMCU_STARTUP := E:\open_source\NammaAUTOSAR/submodules/MCAL/Mcu\src\bsp/startup/rp2040/libMcu_Startup.la
LIBMCU := E:\open_source\NammaAUTOSAR/submodules\MCAL\Mcu/libMcu.la
LIBECUM := E:\open_source\NammaAUTOSAR/submodules\SL\EcuM/libEcuM.la
LIBPORT := E:\open_source\NammaAUTOSAR/submodules\MCAL\Port/libPort.la
LIBDIO := E:\open_source\NammaAUTOSAR/submodules\MCAL\Dio/libDio.la
LIBSPI := E:\open_source\NammaAUTOSAR/submodules\MCAL\Spi/libSpi.la
LIBLIN := E:\open_source\NammaAUTOSAR/submodules\MCAL\Lin/libLin.la
LIBETH := E:\open_source\NammaAUTOSAR/submodules\MCAL\Eth/libEth.la
LIBETHIF := E:\open_source\NammaAUTOSAR/submodules\ECU-AL\EthIf/libEthIf.la
LIBTCPIP := E:\open_source\NammaAUTOSAR/submodules\SL\TcpIp/libTcpIp.la
LIBOS := E:\open_source\NammaAUTOSAR/submodules\SL\Os/libOs.la
LIBNAMMATESTAPP := E:\open_source\NammaAUTOSAR/submodules\AL\NammaTestApp/libNammaTestApp.la


# Link Archive Object List
LA_OBJS :=  $(LIBMCU_STARTUP) $(LIBMCU) $(LIBECUM) $(LIBPORT) $(LIBDIO) $(LIBSPI) $(LIBLIN) \
	    $(LIBETH) $(LIBETHIF) $(LIBTCPIP) $(LIBOS) $(LIBNAMMATESTAPP)
